import React from 'react'
import {
  Box,
  Typography,
  Grid,
  Chip,
  Divider,
  Drawer,
  IconButton,
  Container,
  Card,
  CardContent,
  Stack,
  Alert,
  Paper
} from '@mui/material'
import { 
  DirectionsCar, 
  Build, 
  Person, 
  Close, 
  AttachMoney,
  TrendingUp,
  Assessment,
  Warning,
  Info,
  Star
} from '@mui/icons-material'
import { 
  AIValuationSummary, 
  VehicleHeader, 
  VehicleSpecs, 
  MarketValues
} from './index';
import { parseAnalysisData } from '../../utils/vehicle-analysis-helper';

export const VehicleInfoDrawer = ({ searchResults, onClose, open = false }) => {
  if (!searchResults || (!searchResults.analysis && !searchResults.ai_valuation)) return null

  const parsedAnalysis = parseAnalysisData(searchResults);
  console.log('AFTER parsedAnalysis', parsedAnalysis);
  return (
    <Drawer
      anchor="bottom"
      open={open}
      onClose={onClose}
      PaperProps={{
        sx: {
          bgcolor: '#1A1A1A',
          borderTop: '1px solid #2A2A2A',
          height: '100vh',
          width: '100%',
        }
      }}
    >
      <Box sx={{ 
        height: '100%', 
        overflow: 'auto',
        '&::-webkit-scrollbar': { display: 'none' },
        msOverflowStyle: 'none',
        scrollbarWidth: 'none' 
      }}>
        
        {/* Drawer Header */}
        <Box sx={{ 
          display: 'flex', 
          justifyContent: 'space-between', 
          alignItems: 'center', 
          p: 2,
          borderBottom: '1px solid #2A2A2A',
          position: 'sticky',
          top: 0,
          bgcolor: '#1A1A1A',
          zIndex: 1,
          boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)'
        }}>
          <Typography variant="h6" sx={{ color: '#FFFFFF', fontWeight: 500 }}>
            Vehicle Market Valuation
          </Typography>
          <IconButton
            onClick={onClose}
            sx={{ color: '#A0A0A0' }}
          >
            <Close />
          </IconButton>
        </Box>

        <Container maxWidth="lg" sx={{ py: 3, pb: 5 }}>
          
          {/* Report Header with Metadata */}
          <Card variant="info" sx={{ mb: 3 }}>
            <CardContent>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                <Typography variant="h6" sx={{ color: '#FFFFFF', fontWeight: 600 }}>
                  AI Vehicle Valuation Report
                </Typography>
                <Chip 
                  label={parsedAnalysis.reportId || 'DVai-Report'} 
                  sx={{ 
                    bgcolor: 'rgba(195, 255, 81, 0.2)', 
                    color: '#C3FF51',
                    fontWeight: 500
                  }} 
                />
              </Box>
              <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                Generated by {parsedAnalysis.generatedBy || 'DriveValueAI API v2.0'} • {parsedAnalysis.timestamp ? new Date(parsedAnalysis.timestamp).toLocaleString() : 'Just now'}
              </Typography>
            </CardContent>
          </Card>

          {/* Vehicle Basic Info */}
          <VehicleHeader searchResults={searchResults} parsedAnalysis={parsedAnalysis} />

          {/* AI Valuation Summary - Most Important Section */}
          <AIValuationSummary parsedAnalysis={parsedAnalysis} searchResults={searchResults} />

          {/* Mileage Analysis */}
          {parsedAnalysis.mileage && (
            <Card variant="info" sx={{ mb: 3 }}>
              <CardContent>
                <Typography variant="h6" sx={{ color: '#FFFFFF', mb: 2, display: 'flex', alignItems: 'center' }}>
                  <TrendingUp sx={{ mr: 1, color: '#C3FF51' }} />
                  Mileage Analysis
                </Typography>
                <Grid container spacing={2}>
                  <Grid item xs={12} md={4}>
                    <Box sx={{ textAlign: 'center', p: 2, bgcolor: 'rgba(195, 255, 81, 0.1)', borderRadius: 2 }}>
                      <Typography variant="h4" sx={{ color: '#C3FF51', fontWeight: 700 }}>
                        {parsedAnalysis.mileage.actual?.toLocaleString()}
                      </Typography>
                      <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                        Actual Miles
                      </Typography>
                    </Box>
                  </Grid>
                  <Grid item xs={12} md={4}>
                    <Box sx={{ textAlign: 'center', p: 2, bgcolor: 'rgba(160, 160, 160, 0.1)', borderRadius: 2 }}>
                      <Typography variant="h4" sx={{ color: '#A0A0A0', fontWeight: 700 }}>
                        {parsedAnalysis.mileage.expected?.toLocaleString()}
                      </Typography>
                      <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                        Expected Miles
                      </Typography>
                    </Box>
                  </Grid>
                  <Grid item xs={12} md={4}>
                    <Box sx={{ textAlign: 'center', p: 2, bgcolor: 'rgba(0, 212, 170, 0.1)', borderRadius: 2 }}>
                      <Typography variant="h4" sx={{ color: '#00D4AA', fontWeight: 700 }}>
                        {parsedAnalysis.mileage.variancePercentage}%
                      </Typography>
                      <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                        Below Average
                      </Typography>
                    </Box>
                  </Grid>
                </Grid>
                <Typography variant="body2" sx={{ color: '#A0A0A0', mt: 2, fontStyle: 'italic' }}>
                  This vehicle has {parsedAnalysis.mileage.variancePercentage}% fewer miles than expected for its age, 
                  which significantly enhances its value and desirability in the market.
                </Typography>
              </CardContent>
            </Card>
          )}

          {/* Key Insights */}
          {parsedAnalysis.key_insights && (
            <Card variant="info" sx={{ mb: 3 }}>
              <CardContent>
                <Typography variant="h6" sx={{ color: '#FFFFFF', mb: 2, display: 'flex', alignItems: 'center' }}>
                  <Star sx={{ mr: 1, color: '#C3FF51' }} />
                  Key Market Insights
                </Typography>
                <Grid container spacing={2}>
                  {parsedAnalysis.key_insights.rarity_factors && (
                    <Grid item xs={12} md={6}>
                      <Box sx={{ p: 2, bgcolor: 'rgba(195, 255, 81, 0.05)', borderRadius: 2, border: '1px solid rgba(195, 255, 81, 0.2)' }}>
                        <Typography variant="subtitle2" sx={{ color: '#C3FF51', fontWeight: 600, mb: 1 }}>
                          Rarity Factors
                        </Typography>
                        <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                          {parsedAnalysis.key_insights.rarity_factors}
                        </Typography>
                      </Box>
                    </Grid>
                  )}
                  {parsedAnalysis.key_insights.value_enhancers && (
                    <Grid item xs={12} md={6}>
                      <Box sx={{ p: 2, bgcolor: 'rgba(0, 212, 170, 0.05)', borderRadius: 2, border: '1px solid rgba(0, 212, 170, 0.2)' }}>
                        <Typography variant="subtitle2" sx={{ color: '#00D4AA', fontWeight: 600, mb: 1 }}>
                          Value Enhancers
                        </Typography>
                        <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                          {parsedAnalysis.key_insights.value_enhancers}
                        </Typography>
                      </Box>
                    </Grid>
                  )}
                </Grid>
              </CardContent>
            </Card>
          )}

          {/* AI Market Values */}
          <MarketValues parsedAnalysis={parsedAnalysis} />

          {/* Value Adjustments */}
          {parsedAnalysis.valueAdjustments && (
            <Card variant="info" sx={{ mb: 3 }}>
              <CardContent>
                <Typography variant="h6" sx={{ color: '#FFFFFF', mb: 2, display: 'flex', alignItems: 'center' }}>
                  <Assessment sx={{ mr: 1, color: '#C3FF51' }} />
                  Value Adjustments
                </Typography>
                <Grid container spacing={2}>
                  {Object.entries(parsedAnalysis.valueAdjustments).map(([key, value]) => (
                    key !== 'total_adjustment' && (
                      <Grid item xs={12} md={6} key={key}>
                        <Box sx={{ p: 2, bgcolor: 'rgba(160, 160, 160, 0.05)', borderRadius: 2 }}>
                          <Typography variant="subtitle2" sx={{ color: '#FFFFFF', fontWeight: 600, mb: 1, textTransform: 'capitalize' }}>
                            {key.replace(/_/g, ' ')}
                          </Typography>
                          <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                            {value}
                          </Typography>
                        </Box>
                      </Grid>
                    )
                  ))}
                </Grid>
                {parsedAnalysis.valueAdjustments.total_adjustment && (
                  <Box sx={{ mt: 2, p: 2, bgcolor: 'rgba(195, 255, 81, 0.1)', borderRadius: 2, border: '1px solid rgba(195, 255, 81, 0.3)' }}>
                    <Typography variant="subtitle2" sx={{ color: '#C3FF51', fontWeight: 600, mb: 1 }}>
                      Total Adjustment Impact
                    </Typography>
                    <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                      {parsedAnalysis.valueAdjustments.total_adjustment}
                    </Typography>
                  </Box>
                )}
              </CardContent>
            </Card>
          )}

          {/* Recommendations */}
          {parsedAnalysis.recommendations && (
            <Card variant="info" sx={{ mb: 3 }}>
              <CardContent>
                <Typography variant="h6" sx={{ color: '#FFFFFF', mb: 2, display: 'flex', alignItems: 'center' }}>
                  <Info sx={{ mr: 1, color: '#C3FF51' }} />
                  AI Recommendations
                </Typography>
                <Grid container spacing={2}>
                  {Object.entries(parsedAnalysis.recommendations).map(([key, value]) => (
                    <Grid item xs={12} md={6} key={key}>
                      <Box sx={{ p: 2, bgcolor: 'rgba(160, 160, 160, 0.05)', borderRadius: 2 }}>
                        <Typography variant="subtitle2" sx={{ color: '#FFFFFF', fontWeight: 600, mb: 1, textTransform: 'capitalize' }}>
                          {key.replace(/_/g, ' ')}
                        </Typography>
                        <Typography variant="body2" sx={{ color: '#A0A0A0' }}>
                          {value}
                        </Typography>
                      </Box>
                    </Grid>
                  ))}
                </Grid>
              </CardContent>
            </Card>
          )}

        </Container>
      </Box>
    </Drawer>
  )
}